

server:
  port: 8082
  servlet:
    context-path: /pagamento

spring:
  application:
    name: crud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/microservice-pagamento
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

crud:
  rabbitmq:
    exchange: crud.exchange
    queue: crud.produto.queue
          
   

  #jmx:
   # enabled: false
    