
server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/microservice-crud
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

  #jmx:
   # enabled: false
   
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
   
crud:
  rabbitmq:
    exchange: crud.exchange
    routingkey: crud.produto.routingkey